src/__init__.py
# from .database import db
# from .app import app
#
# db.init_app(app)

src/app.py
import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

import sqlite3

from blueprints.home import home as home_blueprint
from blueprints.thread import thread_bp as thread_blueprint

from database.database import add_post, create_table

from globals import DATABASE_PATH, CURSOR_PATH, ARTIFACTS_DIR, UPLOADS_DIR


if __name__ == '__main__':
    app = Flask(__name__)
    app.debug = True

    app.register_blueprint(home_blueprint)
    app.register_blueprint(thread_blueprint)

    os.makedirs(UPLOADS_DIR, exist_ok=True)
    os.makedirs(ARTIFACTS_DIR, exist_ok=True)

    database_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), os.path.join('..', DATABASE_PATH))
    
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + database_path
    app.config['SECRET_KEY'] = 'secret-key-goes-here'
    app.config['UPLOAD_FOLDER'] = UPLOADS_DIR

    connection = sqlite3.connect(CURSOR_PATH)

    # Populate DB with test thread
    try:
        connection.execute("SELECT * FROM threads;")
    except sqlite3.OperationalError:
        create_table(connection)
        add_post(
            new_thread=True,
            post_content="Hello World",
            sender_ip=None, 
            images=None,
            thread_id=None,
            title="Test thread!"
        )
    
    db = SQLAlchemy()
    db.init_app(app)
    with app.app_context():
        db.create_all()
    
    connection.close
   
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 8080)))

src/blueprints/home.py
from flask import Blueprint, render_template, request, url_for, redirect
from database.database import fetch_all_threads_and_posts, add_post
from utils.data_parsers import parse_content, parse_request_images
from utils.data_rendering import render_all_posts, order_threads_by_recent
from globals import IMAGE_MAX_RESOLUTION_X, IMAGE_MAX_RESOLUTION_Y, MIN_THREAD_TITLE_CHARACTERS, MAX_THREAD_TITLE_CHARACTERS, MIN_THREAD_CONTENT_CHARACTERS, MAX_THREAD_CONTENT_CHARACTERS
from wtforms import Form, SubmitField, TextAreaField, validators

home = Blueprint('home', __name__)

class NewThreadForm(Form):
    title = TextAreaField('Title', validators=[
        validators.InputRequired(message="thread should have a name"), 
        validators.Length(min=MIN_THREAD_TITLE_CHARACTERS, message="thread name is {} characters minimum".format(MIN_THREAD_TITLE_CHARACTERS)), 
        validators.Length(max=MAX_THREAD_TITLE_CHARACTERS, message="thread name is {} characters maximum".format(MAX_THREAD_TITLE_CHARACTERS))],
        render_kw={'rows': 1, 'cols': 50, 'style':'resize:none;','placeholder': 'thread title - {} chars min, {} max'.format(MIN_THREAD_TITLE_CHARACTERS, MAX_THREAD_TITLE_CHARACTERS)})
    content = TextAreaField('Text', validators=[
        validators.InputRequired(message="write something"), 
        validators.Length(min=MIN_THREAD_CONTENT_CHARACTERS, message="thread content is {} characters minimum".format(MIN_THREAD_CONTENT_CHARACTERS)), 
        validators.Length(max=MAX_THREAD_CONTENT_CHARACTERS, message="thread content is {} characters maximum".format(MAX_THREAD_CONTENT_CHARACTERS))], 
        render_kw={'rows': 10, 'cols': 50, 'style':'resize:none;', 'placeholder': 'thread content - {} chars min, {} max\n\npicture is mandatory! max resolution {}x{}, only .jpeg/.jpg/.png/.gif formats\n\nmarkdown supported\n\nfor example:\n\n*this text is italic* and **this text is bold**'.format(MIN_THREAD_CONTENT_CHARACTERS, MAX_THREAD_CONTENT_CHARACTERS,IMAGE_MAX_RESOLUTION_X,IMAGE_MAX_RESOLUTION_Y)})
    submit = SubmitField('create new thread!')

@home.route('/', methods=('GET', 'POST'))
def index():
    form = NewThreadForm(request.form)
    image_error = None
    
    if request.method == 'POST' and form.validate():
        images = parse_request_images(request.files.getlist('image'))
        # this is a weird gimmick but i did try file uploader in the wtforms 
        ## and it did not populate the files to form... idk
        ## TODO: maybe fix this when i have time??? 
        if not images:
            image_error = 'No images uploaded!'
        # TODO: move to a method
        elif any([image['resolution_x'] > IMAGE_MAX_RESOLUTION_X for image in images]) or any([image['resolution_y'] > IMAGE_MAX_RESOLUTION_Y for image in images]):
            image_error = 'Image too big!'
        elif any([image['extension'] not in ['.jpeg', '.gif', '.png', '.jpg'] for image in images]):
            image_error = 'Image file format not supported!'
        else:
            content = parse_content(form.content.data)
            title = form.title.data
            
            new_thread = True
            sender_ip = None
            thread_id = None
            add_post(new_thread, content, sender_ip, images, thread_id, title)
            return redirect(url_for('home.index'))

    threads_and_posts_data = fetch_all_threads_and_posts()
    threads_and_posts_data = order_threads_by_recent(threads_and_posts_data)

    posts_data = [data['posts_data'] for data in threads_and_posts_data]
    threads_data = [data['thread_data'] for data in threads_and_posts_data]
    rendered_posts_data = render_all_posts(posts_data)        
        
    return render_template('index.html', threads=threads_data, posts=rendered_posts_data, form=form, image_error=image_error)

src/blueprints/thread.py
from flask import Blueprint, render_template, request, send_from_directory, url_for, redirect
from database.database import get_posts_by_thread_id, get_thread_data_by_thread_id, add_post
from utils.data_parsers import parse_content, parse_request_images
from utils.data_rendering import render_thread_posts
from wtforms import Form, TextAreaField, SubmitField, validators

from globals import RELATIVE_UPLOADS_DIR, MIN_THREAD_CONTENT_CHARACTERS,MAX_THREAD_CONTENT_CHARACTERS,IMAGE_MAX_RESOLUTION_X,IMAGE_MAX_RESOLUTION_Y

thread_bp = Blueprint('thread', __name__)

class NewPost(Form):
    content = TextAreaField('Text', validators=[
        validators.InputRequired(message="write something"), 
        validators.Length(min=MIN_THREAD_CONTENT_CHARACTERS, message="thread content is {} characters minimum".format(MIN_THREAD_CONTENT_CHARACTERS)), 
        validators.Length(max=MAX_THREAD_CONTENT_CHARACTERS, message="thread content is {} characters maximum".format(MAX_THREAD_CONTENT_CHARACTERS))], 
        render_kw={'rows': 10, 'cols': 50, 'style':'resize:none;', 'placeholder': 'thread content - {} chars min, {} max\n\nmarkdown supported\n\npicture is optional, max resolution {}x{}, only .jpeg/.jpg/.png/.gif formats\n\nto reply to a post do >>postid and (important!) a line break\n\nfor example:\n\n>>2\nyowza!\n*this text is italic* and **this text is bold**'.format(MIN_THREAD_CONTENT_CHARACTERS, MAX_THREAD_CONTENT_CHARACTERS,IMAGE_MAX_RESOLUTION_X,IMAGE_MAX_RESOLUTION_Y)})
    submit = SubmitField('post to thread!')

@thread_bp.route('/uploads/<filename>')
def upload(filename):
    return send_from_directory(RELATIVE_UPLOADS_DIR, filename)

@thread_bp.route('/thread/<thread_id>', methods=['GET', 'POST'])
def thread(thread_id):
    form = NewPost(request.form)

    if request.method == 'POST' and form.validate():

        content = parse_content(form.content.data)
        images = parse_request_images(request.files.getlist('image'))

        new_thread = False
        sender_ip = None
        title = None
        add_post(new_thread, content, sender_ip, images, thread_id, title)
        return redirect(url_for('thread.thread', thread_id=thread_id))
    
    thread_data = get_thread_data_by_thread_id(thread_id)
    thread_posts = get_posts_by_thread_id(thread_id)
    rendered_thread_posts = render_thread_posts(thread_posts)
        
    
    return render_template("thread.html", posts=rendered_thread_posts, thread=thread_data, form=form)

src/templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>

<html>

<body style="background-color:#FFE6F1;padding-top: 170px;">
    <nav class="navbar" style="background-color:white;position:absolute;left:0;right:0;top:0;border-bottom: 1px solid black;">  
            <div style="background-color:#FFE6F1;border-bottom: 1px solid black; font-size: 30px; padding-bottom: 20px; padding-top: 20px">
                <center>
                    CHAN
                </center>
            </div>
        <div class="index_container">  
            <center>
                <div class="index_container_element">
                    <div style="font-size: 20px;">
                        <a href="{{ url_for('home.index') }}" class="index_link" style="color:#FFA4DE">Home</a>
                        <a class="index_link">Link 1</a>
                        <a class="index_link">Link 2</a>
                    </div>
                <div class="index_container_element" style="font-size: 15px;">
                    Hello and welcome to the Chan! 
                    <br>
                    This is a test version.
                </div>
                </div>
            </center>
        </div>  
    </nav>
    {% block content %}
    {% endblock %}
</body>

<style>
    .index_link {
        margin-right:20px;
        margin-left:20px;
    }

    .index_container {
        padding-top: 5px; 
        padding-bottom: 5px; 
        padding-left: 5px; 
        font-size: 20px;
    }

    .index_container_element {
        margin-top:5px;
        margin-bottom:5px;
    }
</style>

</html>

src/templates/index.html
{% from 'macroses/submit_post.html' import submit_post_macro %}
{% from 'macroses/thread.html' import thread_macro %}

{% extends "base.html" %}

{% block content %}

{% set new_thread_form = true %}
{{ submit_post_macro(new_thread_form, form, image_error) }}

{% set threads_count = threads|length %}

{% if threads %}
<div class="threads_index_container">
    {% for i in range(threads_count) %}
            {% set show_full_thread = false %}
            <div class="thread_container">
                {{ thread_macro(threads[i], posts[i], show_full_thread) }}
            </div>
    {% endfor %}
</div>
{% endif %}

<style>

    .threads_index_container {
        margin-top: 0px;
        margin-bottom: 0px;
        display: block;
        flex-direction: column; 
    }

     .thread_container {
        padding-top: 0px;
        padding-bottom: 0px;
        margin-top: 0px;
        margin-bottom: 0px;
        display: flex;
        flex-direction: column;
    }
</style>

{% endblock %}

src/templates/macroses/image_viewer.html
{% macro image_viewer_macro(image, image_index, render_modal_only) %}

{% if render_modal_only %}
    <img id="clickable_image_{{image_index}}">
{% else %}
    <img id="clickable_image_{{image_index}}" src="{{ url_for('thread.upload', filename=image.download_link) }}"
        style="max-width:200px;width:100%;cursor:pointer">
{% endif %}

<div id="modal_{{image_index}}" class="modal">
    <img id="popup_image_{{image_index}}" class="popup_image">
</div>

<style>
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        padding-top: 100px;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
    }

    .popup_image {
        margin: auto;
        display: block;
        width: 400px;
        height: 400px;
        align-items: center;
        justify-content: center;
    }

    /* for small screens */
    @media only screen and (max-width: 700px) {
        .popup_image {
            width: 100%;
        }
    }
</style>

<script>
    var modal = document.getElementById("modal_{{image_index}}");
    console.log(modal)
    modal.addEventListener('click', function () {
        this.style.display = "none";
    })

    var clickableImg = document.getElementById("clickable_image_{{image_index}}");
    var popupImage = document.getElementById("popup_image_{{image_index}}");
    clickableImg.onclick = function () {
        modal.style.display = "block";
        popupImage.src = this.src;
    }
</script>

{% endmacro %}

src/templates/macroses/post.html
{% from 'macroses/image_viewer.html' import image_viewer_macro %}
{% from 'macroses/reply_viewer.html' import reply_viewer_macro %}
{% from 'macroses/post_metadata.html' import post_metadata_macro %}

{% macro post_macro(post, post_id, reply_view_recursion_cycle) %}

{% if post is none %}
    <div>Post not found!</div>
{% else %}
    <div class="mypost">
        {{ post_metadata_macro(post['date_time'], post['id']) }}
        <div class="text_and_images_container">
            {% if post.images|length > 0 %}
                <div class="images_container">
                    {% for image in post.images %}
                        {% set image_index = image['id']|string + "_" + post_id|string %}
                        {% set render_modal_only = false %}
                        <div class="image_and_metadata_container">
                            <div class="image_metadata_container">
                                <a style="font-size: 10px" href="{{ url_for('thread.upload', filename=image.download_link) }}" >{{image.filename}}</a>
                            </div>
                            <div class="image_container">
                                {{ image_viewer_macro(image, image_index, render_modal_only) }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="{{'right_text_container' if post.images|length == 1 else 'bottom_text_container'}}">
            <!-- TODO: reuse the code in the thread_header.html macro -->
                {% for line in post['rendered_content'] %}
                    {% if line.type == 'text' %}
                        {{ line['text'] | safe }}
                    {% else %}
                        {% set reply_popup_id = post_id|string + '_' + reply_view_recursion_cycle|string %}
                        {% set reply_text = line['text'] %}
                        {% set replied_post = line['quoted_post'] %}
                        {{ reply_viewer_macro(reply_text, replied_post, post_id, reply_view_recursion_cycle, reply_popup_id) }}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}

<style>
    .mypost {
        background-color: #E6F4FF;
        padding-top:10px;
        padding-left:5px;
        padding-right:5px;
        border-style: solid;
        border-width: 0.1px;
        border-color: grey;
        margin-bottom: 0px;
        margin-top: 10px;
    }

    .text_and_images_container {
        display: inline-block;
    }

    .images_container {
        display: inline-block;
        padding-top:10px;
    }

    .image_and_metadata_container {
        float: left;
        padding-left:5px;
    }

    .bottom_text_container {
        float: bottom;
        padding-left: 5px;
    }

    .right_text_container {
        float: right;
        padding-left: 20px;
    }

</style>

{% endmacro %}

src/templates/macroses/post_metadata.html
{% macro post_metadata_macro(date_time, post_id) %}

<div class="metadata_container">
    <div class="date_time_container">
        {{ date_time }} 
    </div>
    <div class="post_id_container">
        ID: #{{ post_id }}
    </div>
</div>

<style>
    .metadata_container {
        margin-left: 5px; 
        margin-bottom: 0px;
        font-size: 13px;
    }

    .date_time_container {
        display: inline-block;
        margin-right: 5px;
    }

    .post_id_container {
        display: inline-block;
        font-weight: 500;
        color: palevioletred;
    }
</style>

{% endmacro %}

src/templates/macroses/reply_viewer.html
{% macro reply_viewer_macro(reply, post, post_id, reply_view_recursion_cycle, reply_popup_id) %}

{% from 'macroses/post.html' import post_macro %}

<div id="highlighted_reply{{reply_popup_id}}" class="highlighted_reply">{{reply}}
    <span id="reply_popup{{reply_popup_id}}" class="reply_popup">{{ post_macro(post, post_id, reply_view_recursion_cycle + 1) }}</span>
</div>

<style>
    .highlighted_reply {
        /* position: relative; */
        /* display: inline-block; */
        padding-top: 10px;
        color: #FFA4DE;
    }

    .highlighted_reply .reply_popup {
        visibility: hidden;
        width: 100vw;
        max-width: 10000%;
        color: black;
        border-width: 0.5px;
        position: absolute;
        display: none;
        z-index: 1;
        margin-top:-7%; 
    }

    #highlighted_reply{{reply_popup_id}}:hover #reply_popup{{reply_popup_id}} {
        visibility: visible;
        display: block;
    }

</style> 

{% endmacro %}

src/templates/macroses/submit_post.html
{% macro submit_post_macro(new_thread, form, image_error) %}

<center>
<form method="post" enctype="multipart/form-data" novalidate>
    <div class="form-group">
        <table border="0">
            <tbody>
                {% if new_thread %}
                <tr>
                    <td>
                    {{ form.title(size=20) }}
                    <br>
                    {% for error in form.title.errors %}
                         <span style="color: red;">{{ error }}</span>
                    {% endfor %}
                    </td>
                </tr>
                {% endif %}
                <tr colspan="2">
                    <td colspan="2">
                    {{ form.content(size=100) }}
                    <br>
                    {% for error in form.content.errors %}
                         <span style="color: red;">{{ error }}</span>
                    {% endfor %}
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="custom-file">
                            <input type="file" multiple onchange="previewMultiple(event)" class="custom-file-input"
                                name="image" id="image" accept="image/*">
                            {% if image_error %}
                                <span style="color: red;">{{ image_error }}</span>
                            {% endif %}
                            <div id="galeria">

                            </div>
                            <!-- <img id="output"/> -->
                            <style>
                                #galeria {
                                    display: flex;
                                }

                                #galeria img {
                                    height: 85px;
                                }
                            </style>
                            <script>
                                function previewMultiple(event) {
                                    var saida = document.getElementById("image");
                                    var quantos = saida.files.length;
                                    for (i = 0; i < quantos; i++) {
                                        var urls = URL.createObjectURL(event.target.files[i]);
                                        document.getElementById("galeria").innerHTML += '<img src="' + urls + '">';
                                    }
                                }
                            </script>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <br>
    <p>{{ form.submit() }}</p>
</center>
</form>

<style>
    input[type=file]::file-selector-button {
        padding: .2em .4em;
        border-radius: .2em;
        background-color: lightgrey;
        transition: 1s;
    }

    input[type=file]::file-selector-button:hover {
        background-color: grey;
    }
</style>

{% endmacro %}

src/templates/macroses/thread.html
{% from 'macroses/post.html' import post_macro %}
{% from 'macroses/thread_header.html' import thread_header_macro %}
{% from 'macroses/submit_post.html' import submit_post_macro %}
{% from 'macroses/image_viewer.html' import image_viewer_macro %}

{% macro thread_macro(thread, posts, show_full_thread) %}

{% set reply_view_recursion_cycle = 0 %}
{% set posts_count = posts|length %}
{% set thread_url = thread['id'] %}

{% if show_full_thread %}
    <div class="full_thread_container">
        {% for i in range(posts_count) %}
            {% if i == 0 %}
                {% set post = posts[i] %}
                {{ thread_header_macro(thread['title'], post, post['id'], posts_count, thread_url, show_full_thread) }}
            {% else %}
                {% set post = posts[i] %}
                {{ post_macro(post, post['id'], reply_view_recursion_cycle) }}
            {% endif %}
        {% endfor %}
    </div>
{% else %}
    {% set post = posts[0] %}
    {{ thread_header_macro(thread['title'], post, post['id'], posts_count, thread_url, show_full_thread) }}
    {% if posts_count > 1 %}
        {% set posts_shown = 3 %}
        {% if posts_count < 3 %}
            {% set posts_shown = posts_count %}
        {% endif %}
        {% for i in range(1, posts_shown) %}
            <div class="post_container_index">
                {{ post_macro(posts[i], posts[i]['id'], reply_view_recursion_cycle) }}
            </div>
        {% endfor %}
    {% endif %}
{% endif %}

<style>

    .full_thread_container {
        margin-top: 0px;
        margin-bottom: 0px;
        flex-direction: column; 
    }

    .post_container_index {
        width: 90%;
        margin-left: auto;
    }

</style>

<!-- A gimmick to allow pop-up full-size images in reply view -->

{% set image = none %}
{% set image_index = none %}
{% set render_modal_only = true %}
{{ image_viewer_macro(image, image_index, render_modal_only) }}

{% endmacro %}

src/templates/macroses/thread_header.html
{% from 'macroses/image_viewer.html' import image_viewer_macro %}
{% from 'macroses/reply_viewer.html' import reply_viewer_macro %}
{% from 'macroses/post_metadata.html' import post_metadata_macro %}

{% macro thread_header_macro(thread_title, post, post_id, posts_count, thread_url, show_full_thread) %}

{% set reply_view_recursion_cycle = 0 %}

<div class="thread_header_container">
    <div class="thread_header_metadata_container">
        <div class="thread_header_metadata_title_container">
            {% if not show_full_thread %}
                <a href="{{ url_for('thread.thread', thread_id=thread_url) }}" style="color:#FFA4DE; padding-left: 5px;">{{thread_title}}</a>
                <div class="thread_header_metadata_replies_count_container">
                    ({{posts_count}} replies)
                </div>
            {% else %}
                <div style="color:#FFA4DE; padding-left: 5px;">{{thread_title}}</div>
            {% endif %}
        </div>
        {{ post_metadata_macro(post['date_time'], post['id']) }}
    </div>
    {% if post.images %}
    <div class="thread_header_images_container">
        {% for image in post.images %}
            {% set image_index = image['id']|string + "_" + post_id|string %}
            {% set render_modal_only = false %}
            <div class="thread_header_image_container">
                {{ image_viewer_macro(image, image_index, render_modal_only) }}
            </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="thread_header_text_container">
        <!-- TODO: reuse the code in the post.html macro -->
        {% for line in post['rendered_content'] %}
            {% if line.type == 'text' %}
                {{ line['text'] | safe }}
            {% else %}
                {% set reply_popup_id = post_id|string + '_' + reply_view_recursion_cycle|string %}
                {% set reply_text = line['text'] %}
                {% set replied_post = line['quoted_post'] %}
                {{ reply_viewer_macro(reply_text, replied_post, post_id, reply_view_recursion_cycle, reply_popup_id) }}
            {% endif %}
        {% endfor %}
    </div>
</div>

<style>
    .thread_header_container {
        background-color: #E6F4FF;
        /* padding-bottom:10px; */
        padding-top:10px;
        padding-left:5px;
        padding-right:5px;
        border-style: solid;
        border-width: 0.1px;
        border-color: grey;
        margin-bottom: 0px;
        margin-top: 10px;
    } 

    .thread_header_metadata_container {
        padding-left:0px;
    }

    .thread_header_metadata_title_container {
        font-weight: 900;
        margin-right: 5px;
        margin-bottom: 5px;
        display: inline-block;
    }

    .thread_header_metadata_replies_count_container {
        display: inline-block;
    }

    .thread_header_images_container {
        display: inline-block;
        padding-top:10px;
    }

    .thread_header_image_container {
        float: left;
        padding-left:5px;
    }

    .thread_header_text_container {
        padding-left:5px;
    }

</style>

{% endmacro %}

src/templates/thread.html
{% from 'macroses/thread.html' import thread_macro %}
{% from 'macroses/submit_post.html' import submit_post_macro %}

{% extends "base.html" %}

{% block content %}

{% set new_thread_form = false %}
{% set image_error = false %}
{{ submit_post_macro(new_thread_form, form, image_error) }}

{% set show_full_thread = true %}
{{ thread_macro(thread, posts, show_full_thread) }}

{% endblock %}